sources:
- id: demo_source
  type: telegram_user
  selector:
    include_formats: &id001
    - npvt
    - ovpn
    - conf_lines
    - opaque_bundle
    - npv4
  telegram_user:
    api_id: ${TELEGRAM_API_ID}
    api_hash: ${TELEGRAM_API_HASH}
    session: ${TELEGRAM_USER_SESSION}
    peer: '-1001234567890'
- id: src_1001018853394
  type: telegram_user
  selector:
    include_formats: *id001
  telegram_user:
    api_id: ${TELEGRAM_API_ID}
    api_hash: ${TELEGRAM_API_HASH}
    session: ${TELEGRAM_USER_SESSION}
    peer: '-1001018853394'
- id: src_1001062709660
  type: telegram_user
  selector:
    include_formats: *id001
  telegram_user:
    api_id: ${TELEGRAM_API_ID}
    api_hash: ${TELEGRAM_API_HASH}
    session: ${TELEGRAM_USER_SESSION}
    peer: '-1001062709660'
- id: src_1001094646070
  type: telegram_user
  selector:
    include_formats: *id001
  telegram_user:
    api_id: ${TELEGRAM_API_ID}
    api_hash: ${TELEGRAM_API_HASH}
    session: ${TELEGRAM_USER_SESSION}
    peer: '-1001094646070'
- id: src_1001237997838
  type: telegram_user
  selector:
    include_formats: *id001
  telegram_user:
    api_id: ${TELEGRAM_API_ID}
    api_hash: ${TELEGRAM_API_HASH}
    session: ${TELEGRAM_USER_SESSION}
    peer: '-1001237997838'
- id: src_1001317239872
  type: telegram_user
  selector:
    include_formats: *id001
  telegram_user:
    api_id: ${TELEGRAM_API_ID}
    api_hash: ${TELEGRAM_API_HASH}
    session: ${TELEGRAM_USER_SESSION}
    peer: '-1001317239872'
- id: src_1001421308233
  type: telegram_user
  selector:
    include_formats: *id001
  telegram_user:
    api_id: ${TELEGRAM_API_ID}
    api_hash: ${TELEGRAM_API_HASH}
    session: ${TELEGRAM_USER_SESSION}
    peer: '-1001421308233'
- id: src_1001642221695
  type: telegram_user
  selector:
    include_formats: *id001
  telegram_user:
    api_id: ${TELEGRAM_API_ID}
    api_hash: ${TELEGRAM_API_HASH}
    session: ${TELEGRAM_USER_SESSION}
    peer: '-1001642221695'
- id: src_1001668090000
  type: telegram_user
  selector:
    include_formats: *id001
  telegram_user:
    api_id: ${TELEGRAM_API_ID}
    api_hash: ${TELEGRAM_API_HASH}
    session: ${TELEGRAM_USER_SESSION}
    peer: '-1001668090000'
- id: src_1001684639513
  type: telegram_user
  selector:
    include_formats: *id001
  telegram_user:
    api_id: ${TELEGRAM_API_ID}
    api_hash: ${TELEGRAM_API_HASH}
    session: ${TELEGRAM_USER_SESSION}
    peer: '-1001684639513'
- id: src_1001825199550
  type: telegram_user
  selector:
    include_formats: *id001
  telegram_user:
    api_id: ${TELEGRAM_API_ID}
    api_hash: ${TELEGRAM_API_HASH}
    session: ${TELEGRAM_USER_SESSION}
    peer: '-1001825199550'
- id: src_1002036382771
  type: telegram_user
  selector:
    include_formats: *id001
  telegram_user:
    api_id: ${TELEGRAM_API_ID}
    api_hash: ${TELEGRAM_API_HASH}
    session: ${TELEGRAM_USER_SESSION}
    peer: '-1002036382771'
- id: src_1002086721598
  type: telegram_user
  selector:
    include_formats: *id001
  telegram_user:
    api_id: ${TELEGRAM_API_ID}
    api_hash: ${TELEGRAM_API_HASH}
    session: ${TELEGRAM_USER_SESSION}
    peer: '-1002086721598'
- id: src_1002093246093
  type: telegram_user
  selector:
    include_formats: *id001
  telegram_user:
    api_id: ${TELEGRAM_API_ID}
    api_hash: ${TELEGRAM_API_HASH}
    session: ${TELEGRAM_USER_SESSION}
    peer: '-1002093246093'
- id: src_1002245231279
  type: telegram_user
  selector:
    include_formats: *id001
  telegram_user:
    api_id: ${TELEGRAM_API_ID}
    api_hash: ${TELEGRAM_API_HASH}
    session: ${TELEGRAM_USER_SESSION}
    peer: '-1002245231279'
- id: src_1002258272508
  type: telegram_user
  selector:
    include_formats: *id001
  telegram_user:
    api_id: ${TELEGRAM_API_ID}
    api_hash: ${TELEGRAM_API_HASH}
    session: ${TELEGRAM_USER_SESSION}
    peer: '-1002258272508'
- id: src_1002272946873
  type: telegram_user
  selector:
    include_formats: *id001
  telegram_user:
    api_id: ${TELEGRAM_API_ID}
    api_hash: ${TELEGRAM_API_HASH}
    session: ${TELEGRAM_USER_SESSION}
    peer: '-1002272946873'
- id: src_1002493879683
  type: telegram_user
  selector:
    include_formats: *id001
  telegram_user:
    api_id: ${TELEGRAM_API_ID}
    api_hash: ${TELEGRAM_API_HASH}
    session: ${TELEGRAM_USER_SESSION}
    peer: '-1002493879683'
- id: src_1002743102065
  type: telegram_user
  selector:
    include_formats: *id001
  telegram_user:
    api_id: ${TELEGRAM_API_ID}
    api_hash: ${TELEGRAM_API_HASH}
    session: ${TELEGRAM_USER_SESSION}
    peer: '-1002743102065'
- id: src_1002806337642
  type: telegram_user
  selector:
    include_formats: *id001
  telegram_user:
    api_id: ${TELEGRAM_API_ID}
    api_hash: ${TELEGRAM_API_HASH}
    session: ${TELEGRAM_USER_SESSION}
    peer: '-1002806337642'
- id: src_1002806892134
  type: telegram_user
  selector:
    include_formats: *id001
  telegram_user:
    api_id: ${TELEGRAM_API_ID}
    api_hash: ${TELEGRAM_API_HASH}
    session: ${TELEGRAM_USER_SESSION}
    peer: '-1002806892134'
- id: src_1002857691608
  type: telegram_user
  selector:
    include_formats: *id001
  telegram_user:
    api_id: ${TELEGRAM_API_ID}
    api_hash: ${TELEGRAM_API_HASH}
    session: ${TELEGRAM_USER_SESSION}
    peer: '-1002857691608'
- id: src_1003209702364
  type: telegram_user
  selector:
    include_formats: *id001
  telegram_user:
    api_id: ${TELEGRAM_API_ID}
    api_hash: ${TELEGRAM_API_HASH}
    session: ${TELEGRAM_USER_SESSION}
    peer: '-1003209702364'
- id: src_1003459192517
  type: telegram_user
  selector:
    include_formats: *id001
  telegram_user:
    api_id: ${TELEGRAM_API_ID}
    api_hash: ${TELEGRAM_API_HASH}
    session: ${TELEGRAM_USER_SESSION}
    peer: '-1003459192517'
- id: src_1003744627358
  type: telegram_user
  selector:
    include_formats: *id001
  telegram_user:
    api_id: ${TELEGRAM_API_ID}
    api_hash: ${TELEGRAM_API_HASH}
    session: ${TELEGRAM_USER_SESSION}
    peer: '-1003744627358'
publishing:
  routes:
  - name: demo_output
    from_sources:
    - src_1001018853394
    - src_1001062709660
    - src_1001094646070
    - src_1001237997838
    - src_1001317239872
    - src_1001421308233
    - src_1001642221695
    - src_1001668090000
    - src_1001684639513
    - src_1001825199550
    - src_1002036382771
    - src_1002086721598
    - src_1002093246093
    - src_1002245231279
    - src_1002258272508
    - src_1002272946873
    - src_1002493879683
    - src_1002743102065
    - src_1002806337642
    - src_1002806892134
    - src_1002857691608
    - src_1003209702364
    - src_1003459192517
    - src_1003744627358
    formats:
    - npvt
    destinations:
    - chat_id: '-1001234567890'
      mode: post_on_change
      caption_template: 'Updated: {timestamp}

        SHA: {sha12}'
