sources:
- id: src_1001018853394
  type: telegram_user
  selector:
    include_formats: &id001
    - all
  telegram_user:
    api_id: ${TELEGRAM_API_ID}
    api_hash: ${TELEGRAM_API_HASH}
    session: ${TELEGRAM_USER_SESSION}
    peer: '-1001018853394'
- id: src_1001062709660
  type: telegram_user
  selector:
    include_formats: *id001
  telegram_user:
    api_id: ${TELEGRAM_API_ID}
    api_hash: ${TELEGRAM_API_HASH}
    session: ${TELEGRAM_USER_SESSION}
    peer: '-1001062709660'
- id: src_1001094646070
  type: telegram_user
  selector:
    include_formats: *id001
  telegram_user:
    api_id: ${TELEGRAM_API_ID}
    api_hash: ${TELEGRAM_API_HASH}
    session: ${TELEGRAM_USER_SESSION}
    peer: '-1001094646070'
- id: src_1001237997838
  type: telegram_user
  selector:
    include_formats: *id001
  telegram_user:
    api_id: ${TELEGRAM_API_ID}
    api_hash: ${TELEGRAM_API_HASH}
    session: ${TELEGRAM_USER_SESSION}
    peer: '-1001237997838'
- id: src_1001317239872
  type: telegram_user
  selector:
    include_formats: *id001
  telegram_user:
    api_id: ${TELEGRAM_API_ID}
    api_hash: ${TELEGRAM_API_HASH}
    session: ${TELEGRAM_USER_SESSION}
    peer: '-1001317239872'
- id: src_1001421308233
  type: telegram_user
  selector:
    include_formats: *id001
  telegram_user:
    api_id: ${TELEGRAM_API_ID}
    api_hash: ${TELEGRAM_API_HASH}
    session: ${TELEGRAM_USER_SESSION}
    peer: '-1001421308233'
- id: src_1001642221695
  type: telegram_user
  selector:
    include_formats: *id001
  telegram_user:
    api_id: ${TELEGRAM_API_ID}
    api_hash: ${TELEGRAM_API_HASH}
    session: ${TELEGRAM_USER_SESSION}
    peer: '-1001642221695'
- id: src_1001668090000
  type: telegram_user
  selector:
    include_formats: *id001
  telegram_user:
    api_id: ${TELEGRAM_API_ID}
    api_hash: ${TELEGRAM_API_HASH}
    session: ${TELEGRAM_USER_SESSION}
    peer: '-1001668090000'
- id: src_1001684639513
  type: telegram_user
  selector:
    include_formats: *id001
  telegram_user:
    api_id: ${TELEGRAM_API_ID}
    api_hash: ${TELEGRAM_API_HASH}
    session: ${TELEGRAM_USER_SESSION}
    peer: '-1001684639513'
- id: src_1001825199550
  type: telegram_user
  selector:
    include_formats: *id001
  telegram_user:
    api_id: ${TELEGRAM_API_ID}
    api_hash: ${TELEGRAM_API_HASH}
    session: ${TELEGRAM_USER_SESSION}
    peer: '-1001825199550'
- id: src_1002036382771
  type: telegram_user
  selector:
    include_formats: *id001
  telegram_user:
    api_id: ${TELEGRAM_API_ID}
    api_hash: ${TELEGRAM_API_HASH}
    session: ${TELEGRAM_USER_SESSION}
    peer: '-1002036382771'
- id: src_1002086721598
  type: telegram_user
  selector:
    include_formats: *id001
  telegram_user:
    api_id: ${TELEGRAM_API_ID}
    api_hash: ${TELEGRAM_API_HASH}
    session: ${TELEGRAM_USER_SESSION}
    peer: '-1002086721598'
- id: src_1002093246093
  type: telegram_user
  selector:
    include_formats: *id001
  telegram_user:
    api_id: ${TELEGRAM_API_ID}
    api_hash: ${TELEGRAM_API_HASH}
    session: ${TELEGRAM_USER_SESSION}
    peer: '-1002093246093'
- id: src_1002245231279
  type: telegram_user
  selector:
    include_formats: *id001
  telegram_user:
    api_id: ${TELEGRAM_API_ID}
    api_hash: ${TELEGRAM_API_HASH}
    session: ${TELEGRAM_USER_SESSION}
    peer: '-1002245231279'
- id: src_1002258272508
  type: telegram_user
  selector:
    include_formats: *id001
  telegram_user:
    api_id: ${TELEGRAM_API_ID}
    api_hash: ${TELEGRAM_API_HASH}
    session: ${TELEGRAM_USER_SESSION}
    peer: '-1002258272508'
- id: src_1002272946873
  type: telegram_user
  selector:
    include_formats: *id001
  telegram_user:
    api_id: ${TELEGRAM_API_ID}
    api_hash: ${TELEGRAM_API_HASH}
    session: ${TELEGRAM_USER_SESSION}
    peer: '-1002272946873'
- id: src_1002493879683
  type: telegram_user
  selector:
    include_formats: *id001
  telegram_user:
    api_id: ${TELEGRAM_API_ID}
    api_hash: ${TELEGRAM_API_HASH}
    session: ${TELEGRAM_USER_SESSION}
    peer: '-1002493879683'
- id: src_1002743102065
  type: telegram_user
  selector:
    include_formats: *id001
  telegram_user:
    api_id: ${TELEGRAM_API_ID}
    api_hash: ${TELEGRAM_API_HASH}
    session: ${TELEGRAM_USER_SESSION}
    peer: '-1002743102065'
- id: src_1002806337642
  type: telegram_user
  selector:
    include_formats: *id001
  telegram_user:
    api_id: ${TELEGRAM_API_ID}
    api_hash: ${TELEGRAM_API_HASH}
    session: ${TELEGRAM_USER_SESSION}
    peer: '-1002806337642'
- id: src_1002806892134
  type: telegram_user
  selector:
    include_formats: *id001
  telegram_user:
    api_id: ${TELEGRAM_API_ID}
    api_hash: ${TELEGRAM_API_HASH}
    session: ${TELEGRAM_USER_SESSION}
    peer: '-1002806892134'
- id: src_1002857691608
  type: telegram_user
  selector:
    include_formats: *id001
  telegram_user:
    api_id: ${TELEGRAM_API_ID}
    api_hash: ${TELEGRAM_API_HASH}
    session: ${TELEGRAM_USER_SESSION}
    peer: '-1002857691608'
- id: src_1003209702364
  type: telegram_user
  selector:
    include_formats: *id001
  telegram_user:
    api_id: ${TELEGRAM_API_ID}
    api_hash: ${TELEGRAM_API_HASH}
    session: ${TELEGRAM_USER_SESSION}
    peer: '-1003209702364'
- id: src_1003459192517
  type: telegram_user
  selector:
    include_formats: *id001
  telegram_user:
    api_id: ${TELEGRAM_API_ID}
    api_hash: ${TELEGRAM_API_HASH}
    session: ${TELEGRAM_USER_SESSION}
    peer: '-1003459192517'
- id: src_1003744627358
  type: telegram_user
  selector:
    include_formats: *id001
  telegram_user:
    api_id: ${TELEGRAM_API_ID}
    api_hash: ${TELEGRAM_API_HASH}
    session: ${TELEGRAM_USER_SESSION}
    peer: '-1003744627358'
- id: src_1001796213998
  type: telegram_user
  selector:
    include_formats: *id001
  telegram_user:
    api_id: ${TELEGRAM_API_ID}
    api_hash: ${TELEGRAM_API_HASH}
    session: ${TELEGRAM_USER_SESSION}
    peer: '-1001796213998'
- id: src_1001514302686
  type: telegram_user
  selector:
    include_formats: *id001
  telegram_user:
    api_id: ${TELEGRAM_API_ID}
    api_hash: ${TELEGRAM_API_HASH}
    session: ${TELEGRAM_USER_SESSION}
    peer: '-1001514302686'
- id: src_1001763408915
  type: telegram_user
  selector:
    include_formats: *id001
  telegram_user:
    api_id: ${TELEGRAM_API_ID}
    api_hash: ${TELEGRAM_API_HASH}
    session: ${TELEGRAM_USER_SESSION}
    peer: '-1001763408915'
- id: src_1002564682495
  type: telegram_user
  selector:
    include_formats: *id001
  telegram_user:
    api_id: ${TELEGRAM_API_ID}
    api_hash: ${TELEGRAM_API_HASH}
    session: ${TELEGRAM_USER_SESSION}
    peer: '-1002564682495'
- id: src_1001875619482
  type: telegram_user
  selector:
    include_formats: *id001
  telegram_user:
    api_id: ${TELEGRAM_API_ID}
    api_hash: ${TELEGRAM_API_HASH}
    session: ${TELEGRAM_USER_SESSION}
    peer: '-1001875619482'
- id: src_1002675340099
  type: telegram_user
  selector:
    include_formats: *id001
  telegram_user:
    api_id: ${TELEGRAM_API_ID}
    api_hash: ${TELEGRAM_API_HASH}
    session: ${TELEGRAM_USER_SESSION}
    peer: '-1002675340099'
- id: src_1003705249752
  type: telegram_user
  selector:
    include_formats: *id001
  telegram_user:
    api_id: ${TELEGRAM_API_ID}
    api_hash: ${TELEGRAM_API_HASH}
    session: ${TELEGRAM_USER_SESSION}
    peer: '-1003705249752'
- id: src_1001767284651
  type: telegram_user
  selector:
    include_formats: *id001
  telegram_user:
    api_id: ${TELEGRAM_API_ID}
    api_hash: ${TELEGRAM_API_HASH}
    session: ${TELEGRAM_USER_SESSION}
    peer: '-1001767284651'
- id: src_1002750253398
  type: telegram_user
  selector:
    include_formats: *id001
  telegram_user:
    api_id: ${TELEGRAM_API_ID}
    api_hash: ${TELEGRAM_API_HASH}
    session: ${TELEGRAM_USER_SESSION}
    peer: '-1002750253398'
- id: src_1002094972529
  type: telegram_user
  selector:
    include_formats: *id001
  telegram_user:
    api_id: ${TELEGRAM_API_ID}
    api_hash: ${TELEGRAM_API_HASH}
    session: ${TELEGRAM_USER_SESSION}
    peer: '-1002094972529'
- id: src_1001810074293
  type: telegram_user
  selector:
    include_formats: *id001
  telegram_user:
    api_id: ${TELEGRAM_API_ID}
    api_hash: ${TELEGRAM_API_HASH}
    session: ${TELEGRAM_USER_SESSION}
    peer: '-1001810074293'
- id: src_1002086200619
  type: telegram_user
  selector:
    include_formats: *id001
  telegram_user:
    api_id: ${TELEGRAM_API_ID}
    api_hash: ${TELEGRAM_API_HASH}
    session: ${TELEGRAM_USER_SESSION}
    peer: '-1002086200619'
- id: src_1003336135529
  type: telegram_user
  selector:
    include_formats: *id001
  telegram_user:
    api_id: ${TELEGRAM_API_ID}
    api_hash: ${TELEGRAM_API_HASH}
    session: ${TELEGRAM_USER_SESSION}
    peer: '-1003336135529'
- id: src_1001821423515
  type: telegram_user
  selector:
    include_formats: *id001
  telegram_user:
    api_id: ${TELEGRAM_API_ID}
    api_hash: ${TELEGRAM_API_HASH}
    session: ${TELEGRAM_USER_SESSION}
    peer: '-1001821423515'
- id: src_1001629460620
  type: telegram_user
  selector:
    include_formats: *id001
  telegram_user:
    api_id: ${TELEGRAM_API_ID}
    api_hash: ${TELEGRAM_API_HASH}
    session: ${TELEGRAM_USER_SESSION}
    peer: '-1001629460620'
- id: src_1001436746445
  type: telegram_user
  selector:
    include_formats: *id001
  telegram_user:
    api_id: ${TELEGRAM_API_ID}
    api_hash: ${TELEGRAM_API_HASH}
    session: ${TELEGRAM_USER_SESSION}
    peer: '-1001436746445'
- id: src_1001789702327
  type: telegram_user
  selector:
    include_formats: *id001
  telegram_user:
    api_id: ${TELEGRAM_API_ID}
    api_hash: ${TELEGRAM_API_HASH}
    session: ${TELEGRAM_USER_SESSION}
    peer: '-1001789702327'
- id: src_1001891582980
  type: telegram_user
  selector:
    include_formats: *id001
  telegram_user:
    api_id: ${TELEGRAM_API_ID}
    api_hash: ${TELEGRAM_API_HASH}
    session: ${TELEGRAM_USER_SESSION}
    peer: '-1001891582980'
- id: src_1001266790118
  type: telegram_user
  selector:
    include_formats: *id001
  telegram_user:
    api_id: ${TELEGRAM_API_ID}
    api_hash: ${TELEGRAM_API_HASH}
    session: ${TELEGRAM_USER_SESSION}
    peer: '-1001266790118'
- id: src_1001268460826
  type: telegram_user
  selector:
    include_formats: *id001
  telegram_user:
    api_id: ${TELEGRAM_API_ID}
    api_hash: ${TELEGRAM_API_HASH}
    session: ${TELEGRAM_USER_SESSION}
    peer: '-1001268460826'
- id: src_1001171741566
  type: telegram_user
  selector:
    include_formats: *id001
  telegram_user:
    api_id: ${TELEGRAM_API_ID}
    api_hash: ${TELEGRAM_API_HASH}
    session: ${TELEGRAM_USER_SESSION}
    peer: '-1001171741566'
- id: src_1001896624193
  type: telegram_user
  selector:
    include_formats: *id001
  telegram_user:
    api_id: ${TELEGRAM_API_ID}
    api_hash: ${TELEGRAM_API_HASH}
    session: ${TELEGRAM_USER_SESSION}
    peer: '-1001896624193'
- id: src_1001426238402
  type: telegram_user
  selector:
    include_formats: *id001
  telegram_user:
    api_id: ${TELEGRAM_API_ID}
    api_hash: ${TELEGRAM_API_HASH}
    session: ${TELEGRAM_USER_SESSION}
    peer: '-1001426238402'
- id: src_1001874521308
  type: telegram_user
  selector:
    include_formats: *id001
  telegram_user:
    api_id: ${TELEGRAM_API_ID}
    api_hash: ${TELEGRAM_API_HASH}
    session: ${TELEGRAM_USER_SESSION}
    peer: '-1001874521308'
- id: src_1001825957541
  type: telegram_user
  selector:
    include_formats: *id001
  telegram_user:
    api_id: ${TELEGRAM_API_ID}
    api_hash: ${TELEGRAM_API_HASH}
    session: ${TELEGRAM_USER_SESSION}
    peer: '-1001825957541'
publishing:
  routes:
  - name: all_sources
    from_sources:
    - src_1001018853394
    - src_1001062709660
    - src_1001094646070
    - src_1001237997838
    - src_1001317239872
    - src_1001421308233
    - src_1001642221695
    - src_1001668090000
    - src_1001684639513
    - src_1001825199550
    - src_1002036382771
    - src_1002086721598
    - src_1002093246093
    - src_1002245231279
    - src_1002258272508
    - src_1002272946873
    - src_1002493879683
    - src_1002743102065
    - src_1002806337642
    - src_1002806892134
    - src_1002857691608
    - src_1003209702364
    - src_1003459192517
    - src_1003744627358
    - src_1001796213998
    - src_1001514302686
    - src_1001763408915
    - src_1002564682495
    - src_1001875619482
    - src_1002675340099
    - src_1003705249752
    - src_1001767284651
    - src_1002750253398
    - src_1002094972529
    - src_1001810074293
    - src_1002086200619
    - src_1003336135529
    - src_1001821423515
    - src_1001629460620
    - src_1001436746445
    - src_1001789702327
    - src_1001891582980
    - src_1001266790118
    - src_1001268460826
    - src_1001171741566
    - src_1001896624193
    - src_1001426238402
    - src_1001874521308
    - src_1001825957541
    formats:
    - npvt
    - npvtsub
    - conf_lines
    - ovpn
    - npv4
    - ehi
    - hc
    - hat
    - sip
    - nm
    - dark
    - opaque_bundle
    destinations:
    - chat_id: "8526064109"
      mode: post_on_change
      caption_template: "Merged configs â€“ updated {timestamp}"
